export const MAP_MOVE = 'MAP_MOVE'
export const MAP_SELECT_TRACK = 'MAP_SELECT_TRACK'

export const VIDEO_PLAY_URL = 'VIDEO_PLAY_URL'
export const VIDEO_SEEK = 'VIDEO_SEEK'
export const VIDEO_STOP = 'VIDEO_STOP'

export const VIEWS_UPDATE_LEFT = 'VIEWS_UPDATE_LEFT'
export const VIEWS_UPDATE_RIGHT = 'VIEWS_UPDATE_RIGHT'
export const VIEWS_MAXIMIZE_PANEL = 'VIEWS_MAXIMIZE_PANEL'
export const VIEWS_RESET_PANELS = 'VIEWS_RESET_PANELS'
export const VIEWS_SET_MEDIA_URL = 'VIEWS_SET_MEDIA_URL'
export const VIEWS_SET_TYPE = 'VIEWS_SET_TYPE'

export const CHAT_USER_ENTER = "CHAT_USER_ENTER"
export const CHAT_USER_EXIT = "CHAT_USER_EXIT"
export const CHAT_USER_UPDATE = "CHAT_USER_UPDATE"
export const CHAT_ROOM_JOIN = "CHAT_ROOM_JOIN"
export const CHAT_ROOM_LEAVE = "CHAT_ROOM_LEAVE"
export const CHAT_SELECT_USER = "CHAT_SELECT_USER"
export const CHAT_CONNECT = "CHAT_CONNECT"
export const CHAT_DISCONNECT = "CHAT_DISCONNECT"
export const CHAT_ENABLE_AUDIO = "CHAT_ENABLE_AUDIO"
export const CHAT_ENABLE_VIDEO = "CHAT_ENABLE_VIDEO"
export const CHAT_SHOW_TEXT_CHAT = "CHAT_SHOW_TEXT_CHAT"
export const CHAT_SEND_TEXT_MESSAGE = "CHAT_SEND_TEXT_MESSAGE"
export const CHAT_ADD_TEXT_MESSAGE = "CHAT_ADD_TEXT_MESSAGE"
export const CHAT_CLEAR_TEXT_MESSAGES = "CHAT_CLEAR_TEXT_MESSAGES"

export const CONFIG_JANUS_URL = 'wss://sd6.dcpfs.net:8989/janus'
// export const CONFIG_JANUS_URL = 'ws://localhost:8188/janus'
export const CONFIG_JANUS_ROOM = 9000
export const CONFIG_JANUS_BITRATE = 128000