export const MAP_MOVE = 'MAP_MOVE'
export const MAP_SELECT_TRACK = 'MAP_SELECT_TRACK'

export const VIDEO_PLAY_URL = 'VIDEO_PLAY_URL'
export const VIDEO_SEEK = 'VIDEO_SEEK'
export const VIDEO_STOP = 'VIDEO_STOP'

export const CHAT_USER_ENTER = "CHAT_USER_ENTER"
export const CHAT_USER_EXIT = "CHAT_USER_EXIT"
export const CHAT_USER_UPDATE = "CHAT_USER_UPDATE"
export const CHAT_ROOM_JOIN = "CHAT_ROOM_JOIN"
export const CHAT_ROOM_LEAVE = "CHAT_ROOM_LEAVE"
export const CHAT_SELECT_USER = "CHAT_SELECT_USER"
export const CHAT_CONNECT = "CHAT_CONNECT"
export const CHAT_DISCONNECT = "CHAT_DISCONNECT"
export const CHAT_ENABLE_AUDIO = "CHAT_ENABLE_AUDIO"
export const CHAT_ENABLE_VIDEO = "CHAT_ENABLE_VIDEO"